language: php
sudo: false
php:
  - 7.3
cache:
  directories:
    - "$HOME/.composer/cache/files"
env:
  - SYMFONY_VERSION="4.3.*" DB=mysql
script:
  - php bin/phpunit
services:
  - mysql
install:
  - composer install
  - cp .env.travis .env
