App\Application\Command\RegisterUserCommand:
  constraints:
    - App\Infrastructure\Validator\Symfony\UniqueEntityConstraint:
        entityClass: 'App\Domain\Entity\User'
        fields: [email]
        message: 'user.email.already.exists'
  properties:
    email:
      - NotBlank:
          message: 'user.invalid.email.notBlank'
      - Email:
          message: 'user.invalid.email'
    password:
      - NotBlank:
          message: 'user.invalid.password.notBlank'
      - Length:
          min: 6
          minMessage: 'user.invalid.password.minLength'
          max: 4096
          maxMessage: 'user.invalid.password.maxLength'
