#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
  path: /login_check

createUser:
    path: /user
    controller: App\Controller\RegisterUserController:handleRequest
